### PR TITLE
fix `Unknown` train step

### PR DESCRIPTION
**Pull request by Adk2001tech**
#### Changes

Fixes  (Fixed yielding rate in the generator #129)

#### Type of change

- added while loop in generator.
- added training steps in model training

##### Before- 
model training shoes unknown steps in 1st epoch itself.

Screenshot (45)

<hr><br>

##### After- 
this problem is solved simultaneously with this issue fixection.
Screenshot (47)

### CODE REVIEW

**Comment by aniketmaurya** [comment]
Hi @Adk2001tech, you can update the same PR instead of creating multiple 😀
Let me know if you need any help.

**Comment by Adk2001tech** [comment]
@aniketmaurya can you please clear why this 2 test are failing (codecov/patch)?
thanks

**Comment by Adk2001tech** [comment]
> New code is not covered by unittest that's why code coverage is low

Sir, can you elaborate. still having problem in tacking it.

**Comment by aniketmaurya** [comment]
The tests are written run using `pytest` and test files are present at https://github.com/aniketmaurya/chitra/blob/master/tests/test_trainer.py

Let me do some modifications and merge this for you. May be next time you can add tests.

**Review by aniketmaurya — APPROVED** [review]
Great work

**Pull request merged**
